/*
 * Vencord, a Discord client mod
 * Copyright (c) 2025 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

export const PLUGIN_CATEGORIES = {
    chat_message: [
        "AtSomeone",
        "BetterGifAltText",
        "BetterGifPicker",
        "BetterNotesBox",
        "BetterPlusReacts",
        "CharacterCounter",
        "CopyEmojiMarkdown",
        "CopyFileContents",
        "CtrlEnterSend",
        "DragFavoriteEmotes",
        "FavoriteEmojiFirst",
        "FavoriteGifSearch",
        "GifCollections",
        "GifPaste",
        "GifRoulette",
        "GreetStickerPicker",
        "HideChatButtons",
        "HolyNotes",
        "LimitMiddleClickPaste",
        "MessageBurst",
        "MessageClickActions",
        "MessageColors",
        "MessageTags",
        "MessageTranslate",
        "MoreKaomoji",
        "MoreQuickReactions",
        "MoreStickers",
        "NoBulletPoints",
        "NoMaskedUrlPaste",
        "NoReplyMention",
        "NormalizeMessageLinks",
        "PasteImageLink",
        "PreviewMessage",
        "QuestionMarkReplacement",
        "QuickMention",
        "QuickReply",
        "Quote",
        "RepeatMessages",
        "ReplyTimestamp",
        "SendTimestamps",
        "ShowAllMessageButtons",
        "SilentMessageToggle",
        "SilentTyping",
        "SplitLargeMessages",
        "StickerPaste",
        "TalkInReverse",
        "TextReplace",
        "ToneIndicators",
        "Translate",
        "Translate+",
        "TypingIndicator",
        "TypingTweaks",
        "UniversalMention",
        "UserMessagesPronouns",
        "ValidReply",
        "ValidUser",
        "WhitelistedEmojis",
        "WigglyText",
        "WriteUpperCase"
    ],
    ui_customization: [
        "AccountPanelServerProfile",
        "AlwaysExpandProfiles",
        "AlwaysExpandRoles",
        "BannersEverywhere",
        "BetterActivities",
        "BetterFolders",
        "BetterRoleContext",
        "BetterRoleDot",
        "BetterUserArea",
        "ChannelBadges",
        "ChannelTabs",
        "CleanChannelName",
        "ClientTheme",
        "ColorSighted",
        "CustomFolderIcons",
        "CustomUserColors",
        "Decor",
        "ForceOwnerCrown",
        "FullVCPFP",
        "GlobalBadges",
        "HideServers",
        "IconViewer",
        "MemberCount",
        "MentionAvatars",
        "MoreUserTags",
        "NoMosaic",
        "NoNitroUpsell",
        "NoProfileThemes",
        "NoRoleHeaders",
        "NoSystemBadge",
        "PlainFolderIcon",
        "PlatformIndicators",
        "ServerListIndicators",
        "ShowBadgesInChat",
        "ShowConnections",
        "ShowHiddenChannels",
        "ShowMeYourName",
        "ShowResourceChannels",
        "ShowTimeoutDuration",
        "SidebarChat",
        "Signature",
        "ThemeAttributes",
        "ThemeLibrary",
        "Timezones",
        "Title",
        "UnlockedAvatarZoom",
        "UnreadCountBadge",
        "UserPFP",
        "UserVoiceShow",
        "USRBG",
        "ViewIcons",
        "WallpaperFree"
    ],
    privacy_security: [
        "AlwaysTrust",
        "AnonymiseFileNames",
        "BlockKeywords",
        "ClearURLs",
        "ClientSideBlock",
        "ContentWarning",
        "DisableDeepLinks",
        "HideMedia",
        "IgnoreTerms",
        "ILoveSpam",
        "InvisibleChat",
        "NoBlockedMessages",
        "NoTrack",
        "PlatformSpoofer",
        "RevealAllSpoilers"
    ],
    media: [
        "AppleMusicRichPresence",
        "AudioBookShelfRichPresence",
        "BetterAudioPlayer",
        "BiggerStreamPreview",
        "BlurNSFW",
        "ClipsEnhancements",
        "Dearrow",
        "FixImagesQuality",
        "FixSpotifyEmbeds",
        "FixYoutubeEmbeds",
        "GensokyoRadioRPC",
        "ImageFilename",
        "ImageLink",
        "ImageZoom",
        "ImgToGif",
        "JellyfinRichPresence",
        "LastFMRichPresence",
        "ListenBrainzRPC",
        "MediaPlaybackSpeed",
        "MusicControls",
        "PictureInPicture",
        "ReverseImageSearch",
        "RichMagnetLinks",
        "SaveFavoriteGIFs",
        "ShowSongName",
        "SongLink",
        "SpotifyActivityToggle",
        "SpotifyCrack",
        "SpotifyShareCommands",
        "StatsfmPresence",
        "SteamStatusSync",
        "TidalEmbeds",
        "TosuRPC",
        "UnsuppressEmbeds",
        "VideoToggleBind",
        "VolumeBooster",
        "YoutubeAdblock",
        "YoutubeDescription"
    ],
    voice_notifications: [
        "AltKrispSwitch",
        "AutoDNDWhilePlaying",
        "CallTimer",
        "DisableCallIdle",
        "DisableCameras",
        "ExitSounds",
        "FollowVoiceUser",
        "GameActivityToggle",
        "IgnoreCalls",
        "InstantScreenshare",
        "KeepCurrentChannel",
        "KeywordNotify",
        "MessageNotifier",
        "MicLoopbackTester",
        "NeverPausePreviews",
        "NotificationTitle",
        "NotificationVolume",
        "OnePingPerDM",
        "PingNotifications",
        "RandomVoice",
        "SecretRingToneEnabler",
        "SoundBoardLogger",
        "StatusWhileActive",
        "VcNarrator",
        "VcNarratorCustom",
        "VCPanelSettings",
        "VoiceButtons",
        "VoiceChannelLog",
        "VoiceChatDoubleClick",
        "VoiceChatUtilities",
        "VoiceDownload",
        "VoiceJoinMessages",
        "VoiceMessages",
        "VoiceMessageTranscriber",
        "VoiceRejoin",
        "WhoReacted",
        "WhosWatching",
        "WaitForSlot",
        "ToggleVideoBind",
        "NoPushToTalk",
        "NoDefaultHangStatus",
        "BlockKrisp"
    ],
    server_user_management: [
        "BetterBanReasons",
        "BetterBlockedUsers",
        "BetterInvites",
        "BetterSessions",
        "CopyProfileColors",
        "CopyStatusUrls",
        "CopyStickerLinks",
        "CopyUserMention",
        "CopyUserURLs",
        "FastDeleteChannels",
        "FindReply",
        "FriendCloud",
        "FriendCodes",
        "FriendInvites",
        "FriendshipRanks",
        "FriendsSince",
        "FriendTags",
        "FullSearchContext",
        "FullUserInChatbox",
        "GitHubRepos",
        "GuildPickerDumper",
        "GuildTagSettings",
        "ImplicitRelationships",
        "InRole",
        "InviteDefaults",
        "IRememberYou",
        "JumpTo",
        "LastActive",
        "MutualGroupDMs",
        "NewGuildSettings",
        "NoOnboardingDelay",
        "NoPendingCount",
        "NoUnblockToJump",
        "OverrideForumDefaults",
        "PauseInvitesForever",
        "PermissionFreeWill",
        "PermissionsViewer",
        "PinDMs",
        "RecentDMSwitcher",
        "RelationshipNotifier",
        "ReviewDB",
        "ServerInfo",
        "ServerSearch",
        "ShowTimeoutDuration",
        "SortFriends",
        "ViewRaw"
    ],
    fake_nitro: [
        "FakeNitro",
        "FakeProfileThemes",
        "StickerPaste",
        "UnlimitedAccounts",
        "StreamerModeOn",
        "StreamingCodecDisabler"
    ],
    system_dev: [
        "Anammox",
        "AutoZipper",
        "BetterCommands",
        "BetterSettings",
        "BetterUploadButton",
        "BypassPinPrompt",
        "ConsoleJanitor",
        "ConsoleShortcuts",
        "CrashHandler",
        "CustomIdle",
        "CustomRPC",
        "DevCompanion",
        "DiscordDevBanner",
        "DontRoundMyTimestamps",
        "ElementHighlighter",
        "EquicordHelper",
        "EquicordToolbox",
        "Experiments",
        "ExportMessages",
        "ExpressionCloner",
        "F8Break",
        "FixCodeblockGap",
        "FixFileExtensions",
        "FontLoader",
        "ForwardAnywhere",
        "FrequentQuickSwitcher",
        "GoogleThat",
        "HideChatButtons",
        "IdleAutoRestart",
        "IgnoreActivities",
        "KeyboardNavigation",
        "LoadingQuotes",
        "LoginWithQR",
        "MessageFetchTimer",
        "NewPluginsManager",
        "NoAppsAllowed",
        "NoDevtoolsWarning",
        "NoF1",
        "NoModalAnimation",
        "NoRPC",
        "OpenInApp",
        "OrbolayBridge",
        "PluginsManager",
        "ReactErrorDecoder",
        "ReplaceGoogleSearch",
        "ReplyPingControl",
        "RPCEditor",
        "RPCStats",
        "ScheduledMessages",
        "ScreenRecorder",
        "SearchFix",
        "SelfForward",
        "Settings",
        "ShikiCodeblocks",
        "StartupTimings",
        "StatusPresets",
        "StickerBlocker",
        "SuperReactionTweaks",
        "SupportHelper",
        "Unindent",
        "UnitConverter",
        "UrlHighlighter",
        "ViewRawVariant",
        "WebContextMenus",
        "WebKeybinds",
        "WebpackTarball",
        "WebRichPresence",
        "WebScreenShareFixes"
    ],
    fun: [
        "AlwaysAnimate",
        "Animalese",
        "CursorBuddy",
        "CustomSounds",
        "Equissant",
        "Ghosted",
        "HopOn",
        "Husk",
        "Ingtoninator",
        "IrcColors",
        "Jumpscare",
        "KeyboardSounds",
        "Moyai",
        "PartyMode",
        "PetPet",
        "PolishWording",
        "RemixRevived",
        "SekaiStickers",
        "Snowfall",
        "Soggy",
        "Summaries",
        "TiktokTTS",
        "UwUifier",
        "XSOverlay"
    ]
} as const;

export type PluginCategoryKey = keyof typeof PLUGIN_CATEGORIES;
export type PluginCategory = PluginCategoryKey | "other";

const pluginCategoryKeys = Object.keys(PLUGIN_CATEGORIES) as PluginCategoryKey[];

export const PLUGIN_CATEGORY_ORDER: readonly PluginCategory[] = [...pluginCategoryKeys, "other"];

export const PLUGIN_CATEGORY_LABELS: Record<PluginCategory, string> = {
    chat_message: "💬 - チャット・メッセージ入力・編集",
    ui_customization: "🎨 - 外観・UIカスタマイズ",
    privacy_security: "🔒 - プライバシー・セキュリティ",
    media: "🎵 - メディア・画像・Spotify・YouTube",
    voice_notifications: "🔊 - ボイスチャット(VC)・通知",
    server_user_management: "👥 - サーバー・フレンド・ユーザー管理",
    fake_nitro: "💎 - Nitro擬似機能・制限解除 (Fake系)",
    system_dev: "⚙️ - システム・開発",
    fun: "🎉 - ジョーク・ネタ",
    other: "その他"
};

function normalizePluginName(name: string) {
    return name.toLowerCase().replace(/[^a-z0-9]/g, "");
}

const pluginCategoryLookup = new Map<string, PluginCategoryKey>();

for (const category of pluginCategoryKeys) {
    for (const pluginName of PLUGIN_CATEGORIES[category]) {
        const normalizedPluginName = normalizePluginName(pluginName);
        if (!normalizedPluginName || pluginCategoryLookup.has(normalizedPluginName)) continue;

        pluginCategoryLookup.set(normalizedPluginName, category);
    }
}

export function getPluginCategory(pluginName: string): PluginCategory {
    const normalizedPluginName = normalizePluginName(pluginName);
    if (!normalizedPluginName) return "other";

    return pluginCategoryLookup.get(normalizedPluginName) ?? "other";
}
