blank_issues_enabled: false
contact_links:
    - name: Chocord Support Server
      url: https://equicord.org/discord
      about: If you need help regarding Chocord, please join our support server!
    - name: Chocord Installer
      url: https://github.com/Chocord/Equilotl
      about: You can find the Chocord Installer here
